### ISSUE TITLE
GomWorkers Error

### ISSUE THREAD

**Issue by Cron3x** [Tormak9970/Slicers-GUI#1]
Hi, if i try to proceed with the installation, i get the error can't find module GomWorker.js

(I use windows 11 and npm install doesn't worked)

**Comment by Tormak9970** [comment]
Are you trying to clone the repo and build/edit it or install the app?

**Comment by Cron3x** [comment]
how do i build it? npm start?
I usually don't work with js

**Comment by Tormak9970** [comment]
I don't recommend trying to build the app, you need a lot of stuff installed like GCC, VS_BuildTools_2017 (specifically), and some other stuff. If your issue occurred just trying to install it, then my guess is its related to windows 11, because I tested the newest release and it worked fine for me (on windows 10)

**Comment by Cron3x** [comment]
I have installed the latest version... i will try some other stuff, maybe i find a solution...

**Comment by Tormak9970** [comment]
Alright. I'll check with some other users to see if they have gotten the app to work on windows 11. I don't use it so I don't have a way to test the differences.

**Comment by Tormak9970** [comment]
I have confirmed it should work on windows 11, so it may be an issue with your install/firewall

**Comment by Cron3x** [comment]
That could be it, what exactly ist GomWorkers? I couldn't find it online

**Comment by Tormak9970** [comment]
Its a file in the app: https://github.com/Tormak9970/Slicers-GUI/blob/main/app/src/js/viewers/node-viewer/GomWorker.js

Have u had any of the previous versions installed before?
