### ISSUE TITLE
Some dependencies are outdated

### ISSUE THREAD

**Issue by Acursen** [Tormak9970/Slicers-GUI#2]
This project has some outdated dependencies.
For example, the version of Electron used is 12.2.2, while the latest version is 19.0.7

```
 @codemirror/basic-setup            ^0.18.2         →   ^0.20.0
 @codemirror/commands               ^0.18.3         →   ^6.0.1
 @codemirror/lang-css               ^0.18.0         →   ^6.0.0
 @codemirror/state                  ^0.18.7         →   ^6.1.0
 @codemirror/view                   ^0.18.19        →   ^6.0.2
 @fortawesome/fontawesome-free      ^5.15.3         →   ^6.1.1
 @petamoriken/float16               ^2.0.0          →   ^3.6.5
 electron-edge-js                   ^14.16.1        →   ^17.0.0
 jszip                              ^3.7.1          →   ^3.10.0
 node-gyp                           ^8.2.0          →   ^9.0.0
 three                              ^0.137.0        →   ^0.142.0
 valid-filename                     ^3.1.0          →   ^4.0.0
 @electron-forge/cli                ^6.0.0-beta.63  →   ^6.0.0-beta.64
 @electron-forge/maker-deb          ^6.0.0-beta.63  →   ^6.0.0-beta.64
 @electron-forge/maker-rpm          ^6.0.0-beta.63  →   ^6.0.0-beta.64
 @electron-forge/maker-squirrel     ^6.0.0-beta.63  →   ^6.0.0-beta.64
 @electron-forge/maker-zip          ^6.0.0-beta.63  →   ^6.0.0-beta.64
 electron                           ^12.2.2         →   ^19.0.7
```

**Comment by Tormak9970** [comment]
Hey Acursen. I appreciate you letting me know, however most of these are intentionally not updated

**Comment by Acursen** [comment]
> most of these are intentionally not updated

Could you please explain what the benefit is of not doing this?

**Comment by Tormak9970** [comment]
Sure.

Fontawesome - my license is for that version

electron/forge - going to switch to tauri, so no point in potentially breaking things with an update (electron is know to do that)

node-gyp and edge-js - spent quite a while trying to get these to work with a certain library I have, and now that they do I see no reason to update unless there are security vulnerabilities or new features I need/want

code-mirror - my usage of codemirror is complete, and it was finicky to setup, so unless I need it again in the future, I don't plan on updating it.

To summarize, it saves me time and work to not update these, and unless I have reason to (i.e. vulnerabilities) I see no reason to.
